### ISSUE TITLE
Editing a public (non-private) resource in a dataset fails validation

### ISSUE THREAD

**Issue by cole-fields** [genkimaps/gis-hub#90] opened 2020-11-04 17:52 UTC
@genkimaps I get a message saying that the form has invalid entries. When it is a resource for a private dataset, I do not get this error.

Editing the dataset metadata page is fine, but the resource level metadata throws this error. I can get around it by setting dataset to private, making changes, and then setting back to public, but now the ideal fix. Uncertain about the cause.

![image](https://user-images.githubusercontent.com/52669482/98149587-3f35bc00-1e82-11eb-89da-864f481f77f1.png)

**Comment by genkimaps** [comment] 2020-11-05 08:18
@cole-fields 
The root cause of this issue was this change:  https://github.com/genkimaps/ckanext-scheming/commit/f03fc1c797b7b453db92eef56e34c0d3cc477c9a
The above change was made to fix the weird bug with changes to resources other than the first resource being applied to the first resource (and not being able to edit metadata for the first resource).  That bug is now fixed, but a side effect of this change was to fix the field validation that was previously not working.  One of the validation options for fields in the metadata schema is "require_when_published."  This is somewhat confusing, because internally a CKAN dataset is either not published (i.e. in a draft state, which we call "Private") or published, which we call "Public."  Fields with the `require_when_published` validator are only checked if the dataset is Public.  This explains why you were able to edit resources when the dataset is Private but not when it is Public.  

The weird thing is that all of those fields from your screenshot are dataset-level, not resource-level.  They should be validated when the _dataset_ is edited, but not when a resource is edited.  This tells me that there is still something weird going on the fix that I made in ckanext-scheming.  In any case, those fields have all been disabled for quite a while:  form_snippet and display_snippet are null in the schema, meaning that they are not shown to the user either in the dataset display or in the dataset editing page.  Those fields were added to the schema only to provide compliance with the FGP standard.  I think you have a script that exports data from the GIS Hub and adds the fields needed for FGP, correct? 

To resolve the current issue, I removed the `require_when_published` validator on all of these fields.

**Comment by genkimaps** [comment] 2020-11-07 10:40
@cole-fields To follow up on this, I tried using the latest official version of the ckanext-scheming extension, from:  https://github.com/ckan/ckanext-scheming, but this did not work.  For now, the production server is still using our custom version of the extension, here:  https://github.com/genkimaps/ckanext-scheming/tree/dfo

I updated the wiki page to reflect this:  https://github.com/genkimaps/gis-hub/wiki/DFO's-Custom-CKAN-Site#ckan-scheming-extension

**Comment by cole-fields** [comment] 2020-11-09 23:53
@genkimaps ok, thanks for trying the latest release. sounds like our current solution on the custom version is working after you disabled the `require_when_published` validator

**Closed** 2020-11-11 07:21 UTC
Labels: bug
